# Práctica 26-11-2022
**Nava del Río José Antonio**  
**Ojeda Contreras Braulio Melquisedec**  
**Suárez Pérez Juan Pablo**

In [1]:
# Import the libraries needed
import pandas as pd
from sklearn.model_selection import train_test_split, KFold
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay 
from tabulate import tabulate
import numpy as np
import matplotlib.pyplot as plt

In [2]:
general_results = list()
general_headers = ['Mean Accuracy 3-folds', 'Accuracy Test']
general_indexes = ['emails.csv-Gaussiano', 'emails.csv-Multinomial', 'iris.csv-Gaussiano', 'iris.csv-Multinomial']

In [3]:
class validation_set:
    
    def __init__(self, X_train, y_train, X_test, y_test):
        self.X_train = X_train
        self.y_train = y_train
        self.X_test = X_test
        self.y_test = y_test

In [4]:
def gaussian(X_train, X_test, y_train, y_test):
    clf = GaussianNB()
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_predict)
    return accuracy

In [5]:
def multinomial(X_train, X_test, y_train, y_test):
    clf = MultinomialNB()
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_predict)
    return accuracy    

## EMAILS 

In [6]:
# Get data
df = pd.read_csv('./emails.csv', sep = ',', engine = 'python')
X = df.drop(['Email No.', 'Prediction'], axis = 1).values
y = df['Prediction'].values

In [7]:
# Generate Data Test and Data Train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [8]:
validation_sets = []
kf = KFold(n_splits = 3)
for train_index, test_index in kf.split(X_train):
    X_train_v, X_test_v = X_train[train_index], X_train[test_index]
    y_train_v, y_test_v = y_train[train_index], y_train[test_index]
    validation_sets.append(validation_set(X_train_v, y_train_v, X_test_v, y_test_v))

In [9]:
results_gaussian = list()
results_multinonmial = list()
results = list()
index = ['k-1', 'k-2', 'k-3', 'Mean']
for vs in validation_sets:
    results_gaussian.append(gaussian(vs.X_train, vs.X_test, vs.y_train, vs.y_test))
    results_multinonmial.append(multinomial(vs.X_train, vs.X_test, vs.y_train, vs.y_test)) 
results_gaussian = np.array(results_gaussian)
results_multinonmial = np.array(results_multinonmial)
mean_gaussian = results_gaussian.mean()
mean_multinomial = results_multinonmial.mean()
for i in range(len(results_gaussian)):
    results.append([results_gaussian[i], results_multinonmial[i]])
results.append([mean_gaussian, mean_multinomial])
print(tabulate(results, headers = ['Gaussian', 'Multinomial'], showindex = index))

        Gaussian    Multinomial
----  ----------  -------------
k-1     0.947804       0.945319
k-2     0.942833       0.937862
k-3     0.94942        0.946932
Mean    0.946686       0.943371


In [10]:
result_gaussian_general = gaussian(X_train, X_test, y_train, y_test)
result_multinomial_general = multinomial(X_train, X_test, y_train, y_test)
print('Result Gaussian Test:', result_gaussian_general)
print('Result Multinomial Test:', result_multinomial_general)
general_results.append([mean_gaussian, result_gaussian_general])
general_results.append([mean_multinomial, result_multinomial_general])

Result Gaussian Test: 0.9484536082474226
Result Multinomial Test: 0.9413659793814433


In [11]:
clf1 = GaussianNB()
clf1.fit(X_train, y_train)
target_names = clf1.classes_

In [12]:
clf2 = MultinomialNB()
clf2.fit(X_train, y_train)

MultinomialNB()

### TRAIN GAUSSIAN RESULT 

In [13]:
y_train_predict = clf1.predict(X_train)
print(classification_report(y_train, y_train_predict))
print(confusion_matrix(y_train, y_train_predict, labels = target_names))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      2561
           1       0.90      1.00      0.95      1059

    accuracy                           0.97      3620
   macro avg       0.95      0.98      0.96      3620
weighted avg       0.97      0.97      0.97      3620

[[2447  114]
 [   3 1056]]


### TEST GAUSSIAN RESULT

In [14]:
y_test_predict = clf1.predict(X_test)
print(classification_report(y_test, y_test_predict))
print(confusion_matrix(y_test, y_test_predict, labels = target_names))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96      1111
           1       0.88      0.95      0.91       441

    accuracy                           0.95      1552
   macro avg       0.93      0.95      0.94      1552
weighted avg       0.95      0.95      0.95      1552

[[1054   57]
 [  23  418]]


### TRAIN MULTINOMIAL RESULT

In [15]:
y_train_predict = clf2.predict(X_train)
print(classification_report(y_train, y_train_predict))
print(confusion_matrix(y_train, y_train_predict, labels = target_names))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96      2561
           1       0.89      0.94      0.92      1059

    accuracy                           0.95      3620
   macro avg       0.93      0.95      0.94      3620
weighted avg       0.95      0.95      0.95      3620

[[2435  126]
 [  59 1000]]


### TEST MULTINOMIAL RESULT

In [16]:
y_test_predict = clf2.predict(X_test)
print(classification_report(y_test, y_test_predict))
print(confusion_matrix(y_test, y_test_predict, labels = target_names))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1111
           1       0.86      0.95      0.90       441

    accuracy                           0.94      1552
   macro avg       0.92      0.94      0.93      1552
weighted avg       0.94      0.94      0.94      1552

[[1043   68]
 [  23  418]]


## IRIS 

In [17]:
# Get data
df = pd.read_csv('./iris.csv', sep = ',', engine = 'python')
X = df.drop('species', axis = 1).values
y = df['species'].values

In [18]:
# Generate Data Test and Data Train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [19]:
validation_sets = []
kf = KFold(n_splits = 3)
for train_index, test_index in kf.split(X_train):
    X_train_v, X_test_v = X_train[train_index], X_train[test_index]
    y_train_v, y_test_v = y_train[train_index], y_train[test_index]
    validation_sets.append(validation_set(X_train_v, y_train_v, X_test_v, y_test_v))

In [20]:
results_gaussian = list()
results_multinonmial = list()
results = list()
index = ['k-1', 'k-2', 'k-3', 'Mean']
for vs in validation_sets:
    results_gaussian.append(gaussian(vs.X_train, vs.X_test, vs.y_train, vs.y_test))
    results_multinonmial.append(multinomial(vs.X_train, vs.X_test, vs.y_train, vs.y_test)) 
results_gaussian = np.array(results_gaussian)
results_multinonmial = np.array(results_multinonmial)
mean_gaussian = results_gaussian.mean()
mean_multinomial = results_multinonmial.mean()
for i in range(len(results_gaussian)):
    results.append([results_gaussian[i], results_multinonmial[i]])
results.append([mean_gaussian, mean_multinomial])
print(tabulate(results, headers = ['Gaussian', 'Multinomial'], showindex = index))

        Gaussian    Multinomial
----  ----------  -------------
k-1     0.914286       0.6
k-2     1              0.942857
k-3     0.942857       0.628571
Mean    0.952381       0.72381


In [21]:
result_gaussian_general = gaussian(X_train, X_test, y_train, y_test)
result_multinomial_general = multinomial(X_train, X_test, y_train, y_test)
print('Result Gaussian Test:', result_gaussian_general)
print('Result Multinomial Test:', result_multinomial_general)
general_results.append([mean_gaussian, result_gaussian_general])
general_results.append([mean_multinomial, result_multinomial_general])

Result Gaussian Test: 1.0
Result Multinomial Test: 0.6


In [22]:
clf1 = GaussianNB()
clf1.fit(X_train, y_train)
target_names = clf1.classes_

In [23]:
clf2 = MultinomialNB()
clf2.fit(X_train, y_train)

MultinomialNB()

### TRAIN GAUSSIAN RESULT 

In [24]:
y_train_predict = clf1.predict(X_train)
print(classification_report(y_train, y_train_predict, target_names = target_names))
print(confusion_matrix(y_train, y_train_predict, labels = target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        34
Iris-versicolor       0.91      0.91      0.91        32
 Iris-virginica       0.92      0.92      0.92        39

       accuracy                           0.94       105
      macro avg       0.94      0.94      0.94       105
   weighted avg       0.94      0.94      0.94       105

[[34  0  0]
 [ 0 29  3]
 [ 0  3 36]]


### TEST GAUSSIAN RESULT

In [25]:
y_test_predict = clf1.predict(X_test)
print(classification_report(y_test, y_test_predict, target_names = target_names))
print(confusion_matrix(y_test, y_test_predict, labels = target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      1.00      1.00        18
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


### TRAIN MULTINOMIAL RESULT

In [26]:
y_train_predict = clf2.predict(X_train)
print(classification_report(y_train, y_train_predict, target_names = target_names))
print(confusion_matrix(y_train, y_train_predict, labels = target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        34
Iris-versicolor       1.00      0.03      0.06        32
 Iris-virginica       0.56      1.00      0.72        39

       accuracy                           0.70       105
      macro avg       0.85      0.68      0.59       105
   weighted avg       0.84      0.70      0.61       105

[[34  0  0]
 [ 0  1 31]
 [ 0  0 39]]


### TEST MULTINOMIAL RESULT

In [27]:
y_test_predict = clf2.predict(X_test)
print(classification_report(y_test, y_test_predict, target_names = target_names))
print(confusion_matrix(y_test, y_test_predict, labels = target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.00      0.00      0.00        18
 Iris-virginica       0.38      1.00      0.55        11

       accuracy                           0.60        45
      macro avg       0.46      0.67      0.52        45
   weighted avg       0.45      0.60      0.49        45

[[16  0  0]
 [ 0  0 18]
 [ 0  0 11]]


C:\Users\USUARIO DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USUARIO DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USUARIO DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## GENERAL RESULTS 

In [28]:
print(tabulate(general_results, headers = general_headers, showindex = general_indexes))

                          Mean Accuracy 3-folds    Accuracy Test
----------------------  -----------------------  ---------------
emails.csv-Gaussiano                   0.946686         0.948454
emails.csv-Multinomial                 0.943371         0.941366
iris.csv-Gaussiano                     0.952381         1
iris.csv-Multinomial                   0.72381          0.6
